"""
Test: Commit Loop Integration (MVP Sprint 28)
==============================================
Verifies that the Monstruo can:
1. Create a branch from main
2. Create/update a file in that branch
3. Open a PR from that branch to main

This test runs against the REAL GitHub API using the configured GITHUB_TOKEN.
It creates a test branch, adds a file, opens a PR, then cleans up.

Usage:
    GITHUB_TOKEN=<token> python -m pytest tests/test_commit_loop.py -v
    or:
    GITHUB_TOKEN=<token> python tests/test_commit_loop.py

Target repo: The user's own el-monstruo repo (auto-detected).
"""
import asyncio
import json
import os
import sys
import time

# Add project root to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from tools.github import (
    create_branch,
    create_or_update_file,
    create_pull_request,
    execute_github,
    list_prs,
)

# Auto-detect repo owner from GITHUB_TOKEN
REPO = os.environ.get("TEST_REPO", "")
BRANCH_NAME = f"test/commit-loop-{int(time.time())}"


async def detect_repo():
    """Detect the el-monstruo repo from the authenticated user."""
    import aiohttp
    token = os.environ.get("GITHUB_TOKEN", "")
    if not token:
        print("ERROR: GITHUB_TOKEN not set")
        sys.exit(1)
    headers = {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
    }
    async with aiohttp.ClientSession() as session:
        # Get authenticated user
        async with session.get("https://api.github.com/user", headers=headers) as resp:
            user_data = await resp.json()
            username = user_data.get("login", "")
            print(f"  Authenticated as: {username}")
    return f"{username}/el-monstruo"


async def test_commit_loop():
    """Full integration test of the commit loop."""
    global REPO

    print("\n" + "=" * 60)
    print("  COMMIT LOOP INTEGRATION TEST")
    print("=" * 60)

    # Step 0: Detect repo
    if not REPO:
        print("\n[0] Detecting repository...")
        REPO = await detect_repo()
    print(f"  Target repo: {REPO}")
    print(f"  Branch name: {BRANCH_NAME}")

    # Step 1: Create branch
    print(f"\n[1] Creating branch '{BRANCH_NAME}' from main...")
    result = await create_branch(repo=REPO, branch=BRANCH_NAME, from_branch="main")
    if "error" in result:
        print(f"  FAILED: {result}")
        return False
    print(f"  SUCCESS: Branch created (SHA: {result.get('sha', 'unknown')[:8]})")

    # Step 2: Create file in branch
    print(f"\n[2] Creating test file in branch...")
    file_content = (
        f"# Commit Loop Test\n\n"
        f"This file was created by El Monstruo's commit loop.\n\n"
        f"- Timestamp: {time.strftime('%Y-%m-%d %H:%M:%S UTC', time.gmtime())}\n"
        f"- Branch: {BRANCH_NAME}\n"
        f"- Purpose: Verify autonomous self-modification capability\n"
    )
    result = await create_or_update_file(
        repo=REPO,
        path="tests/commit_loop_proof.md",
        content=file_content,
        message=f"test: commit loop verification [{BRANCH_NAME}]",
        branch=BRANCH_NAME,
    )
    if "error" in result:
        print(f"  FAILED: {result}")
        return False
    print(f"  SUCCESS: File created at tests/commit_loop_proof.md")

    # Step 3: Create PR
    print(f"\n[3] Creating pull request...")
    result = await create_pull_request(
        repo=REPO,
        title=f"[MVP Test] Commit Loop Verification - {BRANCH_NAME}",
        head=BRANCH_NAME,
        base="main",
        body=(
            "## Commit Loop Test\n\n"
            "This PR was created automatically by El Monstruo's commit loop.\n\n"
            "**What this proves:**\n"
            "- The Monstruo can create branches\n"
            "- The Monstruo can write files to branches\n"
            "- The Monstruo can open PRs for human review\n\n"
            "**Next step:** Close this PR (it's just a test) and celebrate.\n\n"
            "---\n"
            "*Generated by El Monstruo MVP Sprint 28 - Commit Loop*"
        ),
    )
    if "error" in result:
        print(f"  FAILED: {result}")
        return False

    pr_number = result.get("number", "?")
    pr_url = result.get("html_url", result.get("url", ""))
    print(f"  SUCCESS: PR #{pr_number} created")
    print(f"  URL: {pr_url}")

    # Summary
    print("\n" + "=" * 60)
    print("  COMMIT LOOP TEST: ALL 3 STEPS PASSED")
    print("=" * 60)
    print(f"\n  Branch: {BRANCH_NAME}")
    print(f"  File: tests/commit_loop_proof.md")
    print(f"  PR: #{pr_number} → {pr_url}")
    print(f"\n  The Monstruo can now modify its own code.")
    print("=" * 60)

    return True


if __name__ == "__main__":
    success = asyncio.run(test_commit_loop())
    sys.exit(0 if success else 1)
