import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../theme/monstruo_theme.dart';
import '../../providers/chat_provider.dart';
import 'genui_renderer.dart';

/// Screen that displays Generative UI components from the agent.
///
/// This is the "detail pane" in foldable mode (OPPO Find N5)
/// or a standalone screen in single-pane mode.
///
/// Shows the latest GenUI component generated by the agent,
/// with a history of previous components scrollable below.
class GenUIScreen extends ConsumerWidget {
  const GenUIScreen({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final chatState = ref.watch(chatProvider);
    
    // Extract GenUI components from messages
    final genuiMessages = chatState.messages
        .where((m) => m.genuiPayload != null)
        .toList()
        .reversed
        .toList();

    return Scaffold(
      backgroundColor: MonstruoTheme.background,
      appBar: AppBar(
        backgroundColor: MonstruoTheme.surface,
        title: const Row(
          children: [
            Icon(Icons.auto_awesome, size: 18, color: MonstruoTheme.primary),
            SizedBox(width: 8),
            Text(
              'Generative UI',
              style: TextStyle(
                fontSize: 16,
                fontWeight: FontWeight.w600,
                color: MonstruoTheme.onBackground,
              ),
            ),
          ],
        ),
        actions: [
          if (genuiMessages.isNotEmpty)
            Padding(
              padding: const EdgeInsets.only(right: 12),
              child: Center(
                child: Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 3),
                  decoration: BoxDecoration(
                    color: MonstruoTheme.primary.withValues(alpha: 0.15),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(
                    '${genuiMessages.length}',
                    style: const TextStyle(
                      fontSize: 12,
                      fontWeight: FontWeight.w600,
                      color: MonstruoTheme.primary,
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
      body: genuiMessages.isEmpty
          ? _EmptyState()
          : ListView.separated(
              padding: const EdgeInsets.all(16),
              itemCount: genuiMessages.length,
              separatorBuilder: (_, __) => const SizedBox(height: 16),
              itemBuilder: (context, index) {
                final msg = genuiMessages[index];
                return Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    // Timestamp
                    Padding(
                      padding: const EdgeInsets.only(bottom: 8),
                      child: Text(
                        _formatTime(msg.timestamp),
                        style: const TextStyle(
                          fontSize: 11,
                          color: MonstruoTheme.onSurfaceDim,
                        ),
                      ),
                    ),
                    // GenUI component
                    GenUIRenderer(
                      payload: msg.genuiPayload!,
                      onAction: (action, data) {
                        // Send action back to kernel via chat
                        ref.read(chatProvider.notifier).sendMessage(
                          '[GenUI Action] $action: ${data.toString()}',
                        );
                      },
                    ),
                    // Description if available
                    if (msg.content.isNotEmpty)
                      Padding(
                        padding: const EdgeInsets.only(top: 8),
                        child: Text(
                          msg.content,
                          style: const TextStyle(
                            fontSize: 13,
                            color: MonstruoTheme.onSurfaceDim,
                            height: 1.4,
                          ),
                        ),
                      ),
                  ],
                );
              },
            ),
    );
  }

  String _formatTime(DateTime time) {
    final now = DateTime.now();
    final diff = now.difference(time);

    if (diff.inMinutes < 1) return 'Ahora';
    if (diff.inMinutes < 60) return 'Hace ${diff.inMinutes}m';
    if (diff.inHours < 24) return 'Hace ${diff.inHours}h';
    return '${time.day}/${time.month} ${time.hour}:${time.minute.toString().padLeft(2, '0')}';
  }
}

class _EmptyState extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          Container(
            width: 80,
            height: 80,
            decoration: BoxDecoration(
              color: MonstruoTheme.primary.withValues(alpha: 0.1),
              borderRadius: BorderRadius.circular(20),
            ),
            child: const Icon(
              Icons.auto_awesome,
              size: 36,
              color: MonstruoTheme.primary,
            ),
          ),
          const SizedBox(height: 20),
          const Text(
            'Generative UI',
            style: TextStyle(
              fontSize: 18,
              fontWeight: FontWeight.w600,
              color: MonstruoTheme.onBackground,
            ),
          ),
          const SizedBox(height: 8),
          const Padding(
            padding: EdgeInsets.symmetric(horizontal: 48),
            child: Text(
              'Cuando el agente genere interfaces dinámicas (gráficas, tablas, formularios), aparecerán aquí.',
              textAlign: TextAlign.center,
              style: TextStyle(
                fontSize: 14,
                color: MonstruoTheme.onSurfaceDim,
                height: 1.5,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
