-- THREAD-IMMUNITY-GATE-v1
-- Ledger de cumplimiento de arranque/cierre de hilos Manus.
-- No es una nueva capa de memoria. Es evidencia operacional externa.
-- RLS ON por defecto (Regla Dura #7 de AGENTS.md, DSC-S-006).
-- Diseño autoría: GPT-5.5 Pro (oráculo externo) verificado binariamente por Hilo B.
-- Ajuste de Hilo B: path canónico migrations/sql/0061_* en lugar de supabase/migrations/* (DSC-S-006 + naming secuencial 4 dígitos).

create table if not exists public.thread_immunity_events (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null,
  thread_id text not null,
  event_type text not null check (
    event_type in (
      'SEED_APPLIED',
      'STARTUP_PASS',
      'STARTUP_FAIL',
      'CLOSE_CANONIZED',
      'CLOSE_FAIL',
      'WATCHDOG_PASS',
      'WATCHDOG_FAIL'
    )
  ),
  topic text,
  summary text,
  canon_statement text,
  evidence jsonb not null default '{}'::jsonb,
  local_receipt_sha256 text,
  created_at timestamptz not null default now()
);

create index if not exists idx_thread_immunity_session
  on public.thread_immunity_events (session_id, created_at desc);

create index if not exists idx_thread_immunity_event_type
  on public.thread_immunity_events (event_type, created_at desc);

create index if not exists idx_thread_immunity_thread
  on public.thread_immunity_events (thread_id, created_at desc);

alter table public.thread_immunity_events enable row level security;

drop policy if exists "thread_immunity_service_all" on public.thread_immunity_events;

create policy "thread_immunity_service_all"
  on public.thread_immunity_events
  for all
  using (auth.role() = 'service_role')
  with check (auth.role() = 'service_role');

comment on table public.thread_immunity_events is
'THREAD-IMMUNITY-GATE-v1: evidence ledger for Manus thread startup/closure compliance. Not memory. Not canon.';

comment on column public.thread_immunity_events.session_id is
'UUID generated by thread_immunity.py start; must be reused at close.';

comment on column public.thread_immunity_events.event_type is
'STARTUP_PASS/CLOSE_CANONIZED/WATCHDOG_* are the binary markers for thread immunity.';
