#!/usr/bin/env python3
"""
Sprint 88 - Seed de 85 productos AGENTES para catastro_agentes.

Construido a partir de:
- bridge/sprint88_matriz_seleccion_6c_2026_05_10.md (matriz 6 criterios)
- DSC-MO-009 (arsenal seleccionable por Catastro)
- Investigación tiempo real al 2026-05-10 (snippets validados)

Cada producto incluye:
- id (slug), nombre, proveedor, dominio
- llm_base_id (FK a catastro_modelos cuando aplica, NULL si agnostico)
- 5 dimensiones tecnicas booleanas
- persistencia_memoria, costo_por_uso_tipico
- subcapacidades, casos_de_uso_primarios
- estado, open_weights
- tier_seed (1=top-5 por dominio para validacion profunda, 2=resto)
- fortalezas, fuentes_evidencia (citation tracking minimo)

Notas de FK llm_base_id:
- Solo se setea si el modelo está en catastro_modelos (verificado contra los 37
  modelos del Sprint 86). Productos que envuelven modelos no catalogados aún
  (Kimi K2.6, Sonar, Sora model, Veo model) tienen llm_base_id=NULL con nota
  en data_extra para Sprint 88.1.
"""
from __future__ import annotations

# Top-5 por dominio (calculado por adopcion + relevancia DSC-MO-009)
TOP5_BY_DOMAIN = {
    "agentes_desarrollo": ["manus", "claude-cowork", "claude-code", "openai-codex", "cursor"],
    "agentes_vibe_coding": ["replit-agent", "lovable", "bolt-new", "v0-vercel", "base44"],
    "agentes_multi_swarm": ["langgraph", "crewai", "autogen", "microsoft-agent-framework", "kimi-k2-6-agent-swarm"],
    "agentes_investigacion": ["perplexity-personal-computer", "comet-browser", "gemini-deep-research", "chatgpt-deep-research", "glean"],
    "agentes_ejecutores": ["n8n-llm", "zapier-agents", "lindy", "gumloop", "twin"],
    "agentes_creacion_audiovisual": ["sora-2", "google-veo-3-1", "runway-gen-4-5", "kling-3-0", "higgsfield"],
    "agentes_branding_diseno": ["ideogram", "recraft", "looka", "kittl", "adobe-firefly"],
    "agentes_marketing_ventas": ["apollo", "clay", "hubspot-breeze", "salesforce-agentforce", "jasper"],
    "interfaces_usuario": ["chatgpt-pro", "claude-ai", "gemini-app", "chatgpt-frontier"],
}


def _is_top5(slug: str, dominio: str) -> int:
    """Retorna tier_seed: 1 si está en top-5 del dominio, 2 si no."""
    return 1 if slug in TOP5_BY_DOMAIN.get(dominio, []) else 2


PRODUCTOS = [
    # ========================================================================
    # A. agentes_desarrollo (16 productos)
    # ========================================================================
    {
        "id": "manus", "nombre": "Manus", "proveedor": "Manus AI",
        "dominio": "agentes_desarrollo",
        "llm_base_id": "claude-opus-4-7",
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["sandbox-ubuntu", "browser-stateful", "filesystem", "shell", "mcp-tools", "skills", "scheduler"],
        "casos_de_uso_primarios": ["full-stack-dev", "research-agente", "deploy-railway", "build-mvps"],
        "fortalezas": ["sandbox-completo", "browser-persistente", "skills-modulares", "secrets-managed"],
        "estado": "production",
    },
    {
        "id": "claude-cowork", "nombre": "Claude Cowork", "proveedor": "Anthropic + Monstruo",
        "dominio": "agentes_desarrollo",
        "llm_base_id": "claude-opus-4-7",
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["computer-use", "anthropic-skills", "claude-projects"],
        "casos_de_uso_primarios": ["doctrina-monstruo", "audit-cross-hilo", "DSC-firmar"],
        "fortalezas": ["doctrinal", "audit-deep", "cross-hilo-bridge"],
        "estado": "production",
    },
    {
        "id": "claude-code", "nombre": "Claude Code", "proveedor": "Anthropic",
        "dominio": "agentes_desarrollo",
        "llm_base_id": "claude-opus-4-7",
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": False,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["cli-agent", "terminal-native", "codebase-search", "edit-files"],
        "casos_de_uso_primarios": ["coding-cli", "debugging", "refactor"],
        "fortalezas": ["terminal-native", "swe-bench-top", "cli-first"],
        "estado": "production",
    },
    {
        "id": "openai-codex", "nombre": "OpenAI Codex (2026)", "proveedor": "OpenAI",
        "dominio": "agentes_desarrollo",
        "llm_base_id": "gpt-5-5",
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["cloud-coding-agent", "github-integration", "pr-creation"],
        "casos_de_uso_primarios": ["cloud-coding", "github-prs", "swe-bench"],
        "fortalezas": ["cloud-native", "github-deep", "openai-stack"],
        "estado": "production",
    },
    {
        "id": "cursor", "nombre": "Cursor", "proveedor": "Anysphere",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "llm_bases_alternativos": ["claude-opus-4-7", "gpt-5-5", "gemini-3-pro"],
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["ide-agente", "composer", "cmd-k", "multi-llm"],
        "casos_de_uso_primarios": ["ide-coding", "agent-mode", "vibe-coding-pro"],
        "fortalezas": ["ide-completo", "multi-llm-router", "composer-mode"],
        "estado": "production",
    },
    {
        "id": "devin", "nombre": "Devin", "proveedor": "Cognition AI",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["autonomous-swe", "browser", "shell", "long-tasks"],
        "casos_de_uso_primarios": ["autonomous-coding", "background-tasks", "PR-end-to-end"],
        "fortalezas": ["autonomia-real", "long-running", "background-execution"],
        "estado": "production",
    },
    {
        "id": "openai-agents-sdk", "nombre": "OpenAI Agents SDK", "proveedor": "OpenAI",
        "dominio": "agentes_desarrollo",
        "llm_base_id": "gpt-5-5",
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["framework", "tool-use", "handoffs", "guardrails"],
        "casos_de_uso_primarios": ["custom-agents", "framework-base"],
        "fortalezas": ["openai-oficial", "sucesor-assistants"],
        "estado": "production",
    },
    {
        "id": "google-adk", "nombre": "Google ADK", "proveedor": "Google",
        "dominio": "agentes_desarrollo",
        "llm_base_id": "gemini-3-pro",
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["framework", "agent-development-kit", "adk"],
        "casos_de_uso_primarios": ["custom-agents-gemini"],
        "fortalezas": ["google-oficial", "vertex-ai-deep"],
        "estado": "production",
    },
    {
        "id": "factory-droid", "nombre": "Factory Droid", "proveedor": "Factory",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["multi-agent-coding", "autonomous-swe"],
        "casos_de_uso_primarios": ["autonomous-multi-agent-coding"],
        "fortalezas": ["multi-agent-architecture"],
        "estado": "production",
    },
    {
        "id": "openclaw", "nombre": "OpenClaw", "proveedor": "OSS Community",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["open-source", "claude-code-compatible"],
        "casos_de_uso_primarios": ["coding-self-hosted"],
        "fortalezas": ["open-source", "self-hostable"],
        "estado": "open-source", "open_weights": True,
    },
    {
        "id": "opencode", "nombre": "OpenCode", "proveedor": "OSS Community",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["open-source", "coding-agent"],
        "casos_de_uso_primarios": ["coding-self-hosted"],
        "fortalezas": ["open-source", "transparent"],
        "estado": "open-source", "open_weights": True,
    },
    {
        "id": "aider", "nombre": "Aider", "proveedor": "OSS Community",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": False,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["terminal-cli", "git-aware"],
        "casos_de_uso_primarios": ["terminal-pair-programming"],
        "fortalezas": ["git-aware", "terminal-native", "open-source"],
        "estado": "open-source", "open_weights": True,
    },
    {
        "id": "augment-code", "nombre": "Augment Code", "proveedor": "Augment",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["enterprise-coding", "context-engine"],
        "casos_de_uso_primarios": ["enterprise-codebase-search"],
        "fortalezas": ["enterprise-context", "large-codebase"],
        "estado": "production",
    },
    {
        "id": "trae", "nombre": "Trae", "proveedor": "Bytedance",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["ide-agentic", "bytedance"],
        "casos_de_uso_primarios": ["ide-coding-bytedance"],
        "fortalezas": ["bytedance-stack", "free-tier"],
        "estado": "production",
    },
    {
        "id": "aws-strands", "nombre": "AWS Strands", "proveedor": "AWS",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["framework", "open-source", "aws-bedrock"],
        "casos_de_uso_primarios": ["custom-agents-aws"],
        "fortalezas": ["aws-oficial", "open-source"],
        "estado": "open-source", "open_weights": True,
    },
    {
        "id": "genspark-claw", "nombre": "Genspark Claw", "proveedor": "Genspark",
        "dominio": "agentes_desarrollo",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["agentic-coding", "browser"],
        "casos_de_uso_primarios": ["full-stack-dev"],
        "fortalezas": ["asia-stack", "innovador"],
        "estado": "production",
    },

    # ========================================================================
    # B. agentes_vibe_coding (6 productos)
    # ========================================================================
    {
        "id": "replit-agent", "nombre": "Replit Agent", "proveedor": "Replit",
        "dominio": "agentes_vibe_coding",
        "llm_base_id": "claude-opus-4-7",
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["build-app-prompt", "deploy-replit", "database"],
        "casos_de_uso_primarios": ["mvp-fast", "no-code-app"],
        "fortalezas": ["build-and-deploy", "all-in-one"],
        "estado": "production",
    },
    {
        "id": "lovable", "nombre": "Lovable", "proveedor": "Lovable",
        "dominio": "agentes_vibe_coding",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["full-stack-prompt", "supabase-integration"],
        "casos_de_uso_primarios": ["startup-mvp", "saas-prototyping"],
        "fortalezas": ["full-stack-instant", "supabase-deep"],
        "estado": "production",
    },
    {
        "id": "bolt-new", "nombre": "Bolt.new", "proveedor": "StackBlitz",
        "dominio": "agentes_vibe_coding",
        "llm_base_id": "claude-opus-4-7",
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["web-build-prompt", "webcontainer"],
        "casos_de_uso_primarios": ["web-mvp", "static-sites"],
        "fortalezas": ["browser-runtime", "instant-deploy"],
        "estado": "production",
    },
    {
        "id": "v0-vercel", "nombre": "V0 (Vercel)", "proveedor": "Vercel",
        "dominio": "agentes_vibe_coding",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["ui-from-prompt", "shadcn", "next-js"],
        "casos_de_uso_primarios": ["ui-design-fast", "react-components"],
        "fortalezas": ["shadcn-deep", "next-js-native"],
        "estado": "production",
    },
    {
        "id": "base44", "nombre": "Base44", "proveedor": "Base44",
        "dominio": "agentes_vibe_coding",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["full-stack-no-code"],
        "casos_de_uso_primarios": ["business-apps-no-code"],
        "fortalezas": ["all-in-one-platform"],
        "estado": "production",
    },
    {
        "id": "taskade-genesis", "nombre": "Taskade Genesis", "proveedor": "Taskade",
        "dominio": "agentes_vibe_coding",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["agent-builder", "workflow-builder"],
        "casos_de_uso_primarios": ["custom-agents-no-code"],
        "fortalezas": ["multi-agent-no-code"],
        "estado": "production",
    },

    # ========================================================================
    # C. agentes_multi_swarm (6 productos)
    # ========================================================================
    {
        "id": "langgraph", "nombre": "LangGraph", "proveedor": "LangChain Inc",
        "dominio": "agentes_multi_swarm",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["framework", "graph-orchestration", "checkpointing", "postgres-saver"],
        "casos_de_uso_primarios": ["custom-orchestration", "graph-workflows"],
        "fortalezas": ["graph-state", "postgres-saver", "open-source", "production-ready"],
        "estado": "open-source", "open_weights": True,
    },
    {
        "id": "crewai", "nombre": "CrewAI", "proveedor": "CrewAI Inc",
        "dominio": "agentes_multi_swarm",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["framework", "crew-based", "role-based-agents"],
        "casos_de_uso_primarios": ["multi-agent-collaboration"],
        "fortalezas": ["role-based", "open-source", "popular"],
        "estado": "open-source", "open_weights": True,
    },
    {
        "id": "autogen", "nombre": "AutoGen / AG2", "proveedor": "Microsoft",
        "dominio": "agentes_multi_swarm",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["framework", "conversational-multi-agent"],
        "casos_de_uso_primarios": ["multi-agent-conversation"],
        "fortalezas": ["microsoft-research", "open-source"],
        "estado": "open-source", "open_weights": True,
    },
    {
        "id": "microsoft-agent-framework", "nombre": "Microsoft Agent Framework", "proveedor": "Microsoft",
        "dominio": "agentes_multi_swarm",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["framework", "azure-integrated", "sucesor-autogen-sk"],
        "casos_de_uso_primarios": ["enterprise-multi-agent"],
        "fortalezas": ["microsoft-oficial-2026", "azure-deep"],
        "estado": "production",
    },
    {
        "id": "kimi-k2-6-agent-swarm", "nombre": "Kimi K2.6 Agent Swarm", "proveedor": "Moonshot AI",
        "dominio": "agentes_multi_swarm",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["multi-enjambre", "100x-throughput", "kimi-k2-6"],
        "casos_de_uso_primarios": ["high-throughput-swarm"],
        "fortalezas": ["DSC-MO-009-mencionado", "multi-enjambre-nativo", "throughput-alto"],
        "estado": "production",
        "data_extra": {"nota": "Modelo Kimi K2.6 base no esta en catastro_modelos. Sprint 88.1 catalogarlo."},
    },
    {
        "id": "semantic-kernel", "nombre": "Semantic Kernel", "proveedor": "Microsoft",
        "dominio": "agentes_multi_swarm",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["framework", "skills", "planners"],
        "casos_de_uso_primarios": ["enterprise-orchestration"],
        "fortalezas": ["microsoft-oficial", "open-source"],
        "estado": "open-source", "open_weights": True,
    },

    # ========================================================================
    # D. agentes_investigacion (8 productos)
    # ========================================================================
    {
        "id": "perplexity-personal-computer", "nombre": "Perplexity Personal Computer", "proveedor": "Perplexity",
        "dominio": "agentes_investigacion",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["computer-use-mac", "browser-stateful", "research-agent"],
        "casos_de_uso_primarios": ["deep-research-mac", "computer-use"],
        "fortalezas": ["lanzamiento-mayo-2026", "mac-native"],
        "estado": "production",
        "data_extra": {"lanzamiento": "2026-05-07", "fuente": "TechCrunch"},
    },
    {
        "id": "comet-browser", "nombre": "Comet Browser", "proveedor": "Perplexity",
        "dominio": "agentes_investigacion",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["browser-agentic", "tab-management", "ai-search"],
        "casos_de_uso_primarios": ["browsing-agentic"],
        "fortalezas": ["browser-nativo", "perplexity-search"],
        "estado": "production",
    },
    {
        "id": "gemini-deep-research", "nombre": "Gemini Deep Research", "proveedor": "Google",
        "dominio": "agentes_investigacion",
        "llm_base_id": "gemini-3-pro",
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["deep-research", "multi-step-research", "report-generation"],
        "casos_de_uso_primarios": ["research-reports"],
        "fortalezas": ["google-search-deep", "long-context"],
        "estado": "production",
    },
    {
        "id": "chatgpt-deep-research", "nombre": "ChatGPT Deep Research", "proveedor": "OpenAI",
        "dominio": "agentes_investigacion",
        "llm_base_id": "gpt-5-5",
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["deep-research", "reasoning-strong"],
        "casos_de_uso_primarios": ["research-reports", "academic"],
        "fortalezas": ["o-series-reasoning", "report-quality"],
        "estado": "production",
    },
    {
        "id": "glean", "nombre": "Glean", "proveedor": "Glean",
        "dominio": "agentes_investigacion",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["enterprise-search", "knowledge-base"],
        "casos_de_uso_primarios": ["enterprise-knowledge-search"],
        "fortalezas": ["enterprise-context", "saas-integrations"],
        "estado": "production",
    },
    {
        "id": "notebooklm", "nombre": "NotebookLM", "proveedor": "Google",
        "dominio": "agentes_investigacion",
        "llm_base_id": "gemini-3-pro",
        "tiene_sandbox": False, "acceso_filesystem": True, "acceso_internet": False,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["doc-grounded-research", "audio-overview"],
        "casos_de_uso_primarios": ["doc-research", "audio-summaries"],
        "fortalezas": ["doc-grounding", "audio-overviews"],
        "estado": "production",
    },
    {
        "id": "exa", "nombre": "Exa", "proveedor": "Exa Labs",
        "dominio": "agentes_investigacion",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["semantic-search", "neural-search-api"],
        "casos_de_uso_primarios": ["api-semantic-search"],
        "fortalezas": ["semantic-search", "developer-friendly"],
        "estado": "production",
    },
    {
        "id": "chatgpt-atlas", "nombre": "ChatGPT Atlas", "proveedor": "OpenAI",
        "dominio": "agentes_investigacion",
        "llm_base_id": "gpt-5-5",
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["browser-chatgpt", "operator"],
        "casos_de_uso_primarios": ["browsing-from-chatgpt"],
        "fortalezas": ["chatgpt-integrado", "operator"],
        "estado": "production",
    },

    # ========================================================================
    # E. agentes_ejecutores (5 productos)
    # ========================================================================
    {
        "id": "n8n-llm", "nombre": "n8n + LLM nodes", "proveedor": "n8n",
        "dominio": "agentes_ejecutores",
        "llm_base_id": None,
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "gratis",
        "subcapacidades": ["workflow-engine", "self-hostable", "llm-nodes"],
        "casos_de_uso_primarios": ["workflow-automation"],
        "fortalezas": ["self-hostable", "open-source", "llm-augmented"],
        "estado": "open-source", "open_weights": True,
    },
    {
        "id": "zapier-agents", "nombre": "Zapier Agents", "proveedor": "Zapier",
        "dominio": "agentes_ejecutores",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["workflow-saas", "8000-apps", "mcp"],
        "casos_de_uso_primarios": ["saas-automation"],
        "fortalezas": ["8000-integrations", "mcp-servers", "monstruo-conectado"],
        "estado": "production",
    },
    {
        "id": "lindy", "nombre": "Lindy", "proveedor": "Lindy",
        "dominio": "agentes_ejecutores",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["operational-agents", "vertical-skills"],
        "casos_de_uso_primarios": ["solopreneur-ops", "email-meeting-agents"],
        "fortalezas": ["solopreneur-friendly", "operational-focus"],
        "estado": "production",
    },
    {
        "id": "gumloop", "nombre": "Gumloop", "proveedor": "Gumloop",
        "dominio": "agentes_ejecutores",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["no-code-agent-builder", "workflow"],
        "casos_de_uso_primarios": ["lead-routing", "crm-updates"],
        "fortalezas": ["no-code", "workflow-friendly"],
        "estado": "production",
    },
    {
        "id": "twin", "nombre": "Twin", "proveedor": "Twin.so",
        "dominio": "agentes_ejecutores",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["sales-outreach", "linkedin-prospecting"],
        "casos_de_uso_primarios": ["sales-outreach-automation"],
        "fortalezas": ["sales-vertical"],
        "estado": "production",
    },

    # ========================================================================
    # F. agentes_creacion_audiovisual (18 productos)
    # ========================================================================
    {
        "id": "sora-2", "nombre": "Sora 2", "proveedor": "OpenAI",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["text-to-video", "cinematic-quality", "image-to-video"],
        "casos_de_uso_primarios": ["video-cinematico-corto", "vfx"],
        "fortalezas": ["calidad-cine", "openai-stack"],
        "estado": "production",
        "data_extra": {"nota": "Modelo Sora-2 no en catastro_modelos. Sprint 88.1."},
    },
    {
        "id": "google-veo-3-1", "nombre": "Google Veo 3.1", "proveedor": "Google",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["text-to-video", "audio-nativo", "cinematic-realism"],
        "casos_de_uso_primarios": ["cine-realistic", "audio-sync"],
        "fortalezas": ["audio-nativo", "cinematic-realism"],
        "estado": "production",
    },
    {
        "id": "runway-gen-4-5", "nombre": "Runway Gen-4.5", "proveedor": "Runway",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["text-to-video", "image-to-video", "act-one", "video-editing"],
        "casos_de_uso_primarios": ["filmmaker-suite", "rapid-prototyping"],
        "fortalezas": ["filmmaker-tools", "1-en-benchmarks-2026"],
        "estado": "production",
    },
    {
        "id": "kling-3-0", "nombre": "Kling 3.0", "proveedor": "Kuaishou",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["text-to-video", "free-tier", "high-quality"],
        "casos_de_uso_primarios": ["video-generation-affordable"],
        "fortalezas": ["mejor-relacion-calidad-precio", "free-tier"],
        "estado": "production",
    },
    {
        "id": "pika-2-0", "nombre": "Pika 2.0", "proveedor": "Pika Labs",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["text-to-video", "scene-ingredients"],
        "casos_de_uso_primarios": ["short-form-video"],
        "fortalezas": ["scene-control", "creator-tools"],
        "estado": "production",
    },
    {
        "id": "higgsfield", "nombre": "Higgsfield", "proveedor": "Higgsfield AI",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["studio-cinema-ai", "drama-vertical-9-16", "ugc-ads"],
        "casos_de_uso_primarios": ["short-drama-series", "ugc-ads", "performance-marketing"],
        "fortalezas": ["studio-completo", "vertical-drama", "performance-marketing"],
        "estado": "production",
    },
    {
        "id": "luma-dream-machine", "nombre": "Luma Dream Machine", "proveedor": "Luma AI",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["text-to-video", "ray-2"],
        "casos_de_uso_primarios": ["video-generation"],
        "fortalezas": ["ray-2-model", "consistency"],
        "estado": "production",
    },
    {
        "id": "seedance-2-0", "nombre": "Seedance 2.0", "proveedor": "Bytedance",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["text-to-video", "audio-unificado", "character-consistency"],
        "casos_de_uso_primarios": ["video-cinematic-with-audio"],
        "fortalezas": ["primer-modelo-sounds-as-good", "character-consistency"],
        "estado": "production",
    },
    {
        "id": "heygen", "nombre": "HeyGen", "proveedor": "HeyGen",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["avatar-ai", "text-to-video-avatar", "ugc"],
        "casos_de_uso_primarios": ["avatar-ugc", "marketing-videos"],
        "fortalezas": ["avatares-realistas", "monstruo-tiene-api-key"],
        "estado": "production",
    },
    {
        "id": "synthesia", "nombre": "Synthesia", "proveedor": "Synthesia",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["avatar-ai", "training-videos", "corporate"],
        "casos_de_uso_primarios": ["corporate-training", "explainer-videos"],
        "fortalezas": ["enterprise-friendly", "compliance"],
        "estado": "production",
    },
    {
        "id": "adobe-firefly-creative-agent", "nombre": "Adobe Firefly Creative Agent", "proveedor": "Adobe",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["adobe-suite-orchestrator", "photoshop-integrated"],
        "casos_de_uso_primarios": ["adobe-suite-automation"],
        "fortalezas": ["adobe-deep-integration"],
        "estado": "production",
    },
    {
        "id": "elevenlabs-music", "nombre": "ElevenLabs Music", "proveedor": "ElevenLabs",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["music-generation", "licensing-clean"],
        "casos_de_uso_primarios": ["soundtrack-comercial-legal"],
        "fortalezas": ["licensing-clean-merlin-kobalt", "monstruo-tiene-api-key"],
        "estado": "production",
    },
    {
        "id": "suno", "nombre": "Suno", "proveedor": "Suno",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["text-to-music", "vocals", "lyrics"],
        "casos_de_uso_primarios": ["song-creation"],
        "fortalezas": ["vocals-quality", "popular"],
        "estado": "production",
    },
    {
        "id": "udio", "nombre": "Udio", "proveedor": "Udio",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["text-to-music"],
        "casos_de_uso_primarios": ["song-creation"],
        "fortalezas": ["audio-quality"],
        "estado": "production",
    },
    {
        "id": "aiva", "nombre": "AIVA", "proveedor": "AIVA",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["instrumental-music", "soundtrack"],
        "casos_de_uso_primarios": ["soundtrack-instrumental"],
        "fortalezas": ["instrumental-focus"],
        "estado": "production",
    },
    {
        "id": "stable-audio", "nombre": "Stable Audio", "proveedor": "Stability AI",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["text-to-audio", "sfx", "music"],
        "casos_de_uso_primarios": ["sfx-generation"],
        "fortalezas": ["sfx-quality"],
        "estado": "production",
    },
    {
        "id": "inworld-tts-2", "nombre": "Inworld TTS-2", "proveedor": "Inworld AI",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["realtime-voice", "tts"],
        "casos_de_uso_primarios": ["voice-realtime"],
        "fortalezas": ["realtime-low-latency"],
        "estado": "production",
    },
    {
        "id": "ace-studio-video-composer", "nombre": "Ace Studio Video Composer", "proveedor": "Ace Studio",
        "dominio": "agentes_creacion_audiovisual",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["video-music-sfx-integrated"],
        "casos_de_uso_primarios": ["all-in-one-music-video"],
        "fortalezas": ["video-music-sfx-en-uno"],
        "estado": "production",
    },

    # ========================================================================
    # G. agentes_branding_diseno (10 productos)
    # ========================================================================
    {
        "id": "ideogram", "nombre": "Ideogram", "proveedor": "Ideogram",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["text-in-images", "logo-design", "posters"],
        "casos_de_uso_primarios": ["logos-with-text", "posters", "social-graphics"],
        "fortalezas": ["text-accuracy-90pct", "lider-2026"],
        "estado": "production",
    },
    {
        "id": "recraft", "nombre": "Recraft", "proveedor": "Recraft",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["vector-design", "logo-svg", "brand-style"],
        "casos_de_uso_primarios": ["logos-vector", "brand-assets"],
        "fortalezas": ["vector-nativo", "svg-output", "pro-stack-2026"],
        "estado": "production",
    },
    {
        "id": "looka", "nombre": "Looka", "proveedor": "Looka",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["logo-maker", "brand-kit"],
        "casos_de_uso_primarios": ["logo-mainstream", "brand-kit"],
        "fortalezas": ["mainstream-friendly", "all-in-one"],
        "estado": "production",
    },
    {
        "id": "brandmark", "nombre": "Brandmark", "proveedor": "Brandmark",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["logo-maker", "brand-identity"],
        "casos_de_uso_primarios": ["logo-from-keyword"],
        "fortalezas": ["fast-output"],
        "estado": "production",
    },
    {
        "id": "kittl", "nombre": "Kittl", "proveedor": "Kittl",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["brand-identity-suite", "editorial-control"],
        "casos_de_uso_primarios": ["full-brand-identity"],
        "fortalezas": ["editorial-control", "templates"],
        "estado": "production",
    },
    {
        "id": "brandify", "nombre": "Brandify (App Store)", "proveedor": "Brandify",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["mobile-logo-maker"],
        "casos_de_uso_primarios": ["mobile-logo-creation"],
        "fortalezas": ["mobile-first"],
        "estado": "production",
    },
    {
        "id": "galileo-ai-stitch", "nombre": "Galileo AI / Stitch", "proveedor": "Google (Galileo)",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["ui-design-from-prompt", "figma-export"],
        "casos_de_uso_primarios": ["ui-mockups"],
        "fortalezas": ["ui-ux-deep", "google-acquired"],
        "estado": "production",
    },
    {
        "id": "magicpath", "nombre": "Magicpath", "proveedor": "Magicpath",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["ui-design-from-prompt"],
        "casos_de_uso_primarios": ["ui-mockups"],
        "fortalezas": ["ui-fast"],
        "estado": "production",
    },
    {
        "id": "adobe-firefly", "nombre": "Adobe Firefly", "proveedor": "Adobe",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["image-gen", "photoshop-integrated", "brand-style"],
        "casos_de_uso_primarios": ["hero-images", "brand-design"],
        "fortalezas": ["adobe-suite-deep", "commercial-safe"],
        "estado": "production",
    },
    {
        "id": "nextify", "nombre": "Nextify (slogan/tagline)", "proveedor": "Nextify",
        "dominio": "agentes_branding_diseno",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": False, "multi_swarm_capable": False,
        "persistencia_memoria": "session", "costo_por_uso_tipico": "bajo",
        "subcapacidades": ["slogan-maker", "tagline-generator"],
        "casos_de_uso_primarios": ["ad-copy-from-product-photo"],
        "fortalezas": ["slogan-vertical"],
        "estado": "production",
    },

    # ========================================================================
    # H. agentes_marketing_ventas (11 productos)
    # ========================================================================
    {
        "id": "apollo", "nombre": "Apollo", "proveedor": "Apollo.io",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["lead-database", "email-finder", "outreach"],
        "casos_de_uso_primarios": ["lead-generation", "outbound-sales"],
        "fortalezas": ["base-datos-leads", "email-verificado"],
        "estado": "production",
    },
    {
        "id": "clay", "nombre": "Clay", "proveedor": "Clay",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["data-enrichment", "personalization", "orchestration"],
        "casos_de_uso_primarios": ["enrichment", "personalized-outreach"],
        "fortalezas": ["data-orchestration", "personalization-1-1"],
        "estado": "production",
    },
    {
        "id": "outreach", "nombre": "Outreach", "proveedor": "Outreach.io",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["sales-engagement", "sequences"],
        "casos_de_uso_primarios": ["sales-engagement"],
        "fortalezas": ["enterprise-sales", "sequences"],
        "estado": "production",
    },
    {
        "id": "salesloft", "nombre": "Salesloft", "proveedor": "Salesloft",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["sales-engagement", "cadences"],
        "casos_de_uso_primarios": ["sales-engagement"],
        "fortalezas": ["enterprise-sales"],
        "estado": "production",
    },
    {
        "id": "zoominfo", "nombre": "ZoomInfo", "proveedor": "ZoomInfo",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["b2b-data", "ai-intent"],
        "casos_de_uso_primarios": ["b2b-data-intent"],
        "fortalezas": ["b2b-data-deep"],
        "estado": "production",
    },
    {
        "id": "salesforce-agentforce", "nombre": "Salesforce Agentforce", "proveedor": "Salesforce",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": True,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["crm-agentic", "data-cloud", "atlas-engine"],
        "casos_de_uso_primarios": ["crm-automation", "service-agents"],
        "fortalezas": ["salesforce-deep", "atlas-engine"],
        "estado": "production",
    },
    {
        "id": "sierra", "nombre": "Sierra", "proveedor": "Sierra AI",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["customer-service", "voice-text"],
        "casos_de_uso_primarios": ["customer-service-agentic"],
        "fortalezas": ["bret-taylor-founder", "customer-service-vertical"],
        "estado": "production",
    },
    {
        "id": "hubspot-breeze", "nombre": "HubSpot Breeze", "proveedor": "HubSpot",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["crm-ai", "content-agent", "social-agent"],
        "casos_de_uso_primarios": ["smb-marketing-automation"],
        "fortalezas": ["smb-friendly", "all-in-one-marketing"],
        "estado": "production",
    },
    {
        "id": "decagon", "nombre": "Decagon", "proveedor": "Decagon",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["customer-service-agent"],
        "casos_de_uso_primarios": ["customer-service-vertical"],
        "fortalezas": ["enterprise-cs"],
        "estado": "production",
    },
    {
        "id": "harvey", "nombre": "Harvey", "proveedor": "Harvey AI",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "external_db", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["legal-vertical-agent"],
        "casos_de_uso_primarios": ["legal-research", "legal-docs"],
        "fortalezas": ["legal-vertical", "enterprise"],
        "estado": "production",
    },
    {
        "id": "jasper", "nombre": "Jasper", "proveedor": "Jasper AI",
        "dominio": "agentes_marketing_ventas",
        "llm_base_id": None,
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["marketing-copy", "brand-voice"],
        "casos_de_uso_primarios": ["marketing-content-copywriting"],
        "fortalezas": ["marketing-copy-deep", "brand-voice"],
        "estado": "production",
    },

    # ========================================================================
    # I. interfaces_usuario (4 productos)
    # ========================================================================
    {
        "id": "chatgpt-pro", "nombre": "ChatGPT Pro", "proveedor": "OpenAI",
        "dominio": "interfaces_usuario",
        "llm_base_id": "gpt-5-5",
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "alto",
        "subcapacidades": ["chat", "operator", "codex", "atlas-browser", "deep-research"],
        "casos_de_uso_primarios": ["consumer-pro-chat"],
        "fortalezas": ["operator-incluido", "atlas-browser", "todo-en-uno"],
        "estado": "production",
    },
    {
        "id": "claude-ai", "nombre": "Claude.ai", "proveedor": "Anthropic",
        "dominio": "interfaces_usuario",
        "llm_base_id": "claude-opus-4-7",
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["chat", "computer-use", "artifacts", "projects", "skills"],
        "casos_de_uso_primarios": ["consumer-pro-chat"],
        "fortalezas": ["computer-use", "artifacts", "skills-modulares"],
        "estado": "production",
    },
    {
        "id": "gemini-app", "nombre": "Gemini App", "proveedor": "Google",
        "dominio": "interfaces_usuario",
        "llm_base_id": "gemini-3-pro",
        "tiene_sandbox": False, "acceso_filesystem": False, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "medio",
        "subcapacidades": ["chat", "live", "canvas", "deep-research"],
        "casos_de_uso_primarios": ["consumer-multimodal"],
        "fortalezas": ["live-multimodal", "canvas", "google-stack"],
        "estado": "production",
    },
    {
        "id": "chatgpt-frontier", "nombre": "ChatGPT Frontier", "proveedor": "OpenAI",
        "dominio": "interfaces_usuario",
        "llm_base_id": "gpt-5-5",
        "tiene_sandbox": True, "acceso_filesystem": True, "acceso_internet": True,
        "multi_step_capable": True, "multi_swarm_capable": False,
        "persistencia_memoria": "persistent", "costo_por_uso_tipico": "enterprise",
        "subcapacidades": ["enterprise-platform", "frontier-models"],
        "casos_de_uso_primarios": ["enterprise-deployment"],
        "fortalezas": ["enterprise", "frontier-models-priority"],
        "estado": "production",
    },
]


def get_total() -> int:
    return len(PRODUCTOS)


def attach_tier_seed():
    """Aplica el tier_seed (1=top-5 por dominio, 2=resto) a cada producto."""
    for p in PRODUCTOS:
        p["tier_seed"] = _is_top5(p["id"], p["dominio"])
    return PRODUCTOS


if __name__ == "__main__":
    attach_tier_seed()
    print(f"TOTAL: {get_total()} productos")
    by_dom = {}
    for p in PRODUCTOS:
        by_dom.setdefault(p["dominio"], 0)
        by_dom[p["dominio"]] += 1
    for d, c in sorted(by_dom.items()):
        t1 = sum(1 for p in PRODUCTOS if p["dominio"] == d and p["tier_seed"] == 1)
        t2 = sum(1 for p in PRODUCTOS if p["dominio"] == d and p["tier_seed"] == 2)
        print(f"  {d}: {c} (T1={t1}, T2={t2})")
